export const SCAN_APPROVAL = 'scan_approval'
export const DATA_EXTRACTION = 'data_extraction'
export const DATA_APPROVAL = 'data_approval'
export const INVENTORY_UPDATE = 'inventory_update'
export const INBOUND_MESSAGES = 'inbound_messages'
export const OUTBOUND_MESSAGES = 'outbound_messages'
